### ISSUE TITLE
Derive 2d CAPE from a 3d field of pressure, temperature and humidity

### ISSUE THREAD

**Issue by adybbroe** [tjlang/SkewT#3]
I have come across your nice library recently, in a project where we want to derive CAPE from IASI (hyperspectral sounder satellite instrument) data. I can input one IASI profile and get out a CAPE value, which is nice. But If I want to do it on the entire satellite scan, it is inefficient as it is now.

So I am currently trying porting your library so that it can take 3d fields of pressure, temperature and humidity rather than (only) 1d profiles. I am not sure how difficult it is with just pure Numpy, but I will give it a try and see how far I can get. 

But, perhaps you already know how this can be done, or you have perhaps some thoughts?

**Comment by tjlang** [comment]
Hmmm ... Yeah, I've not tried that before. Should be doable with `numpy` by broadcasting the integrations, but I imagine this particular package is not optimized for it. You could also take a look at MetPy (https://unidata.github.io/MetPy/latest/) and/or SHARPpy (https://github.com/sharppy/SHARPpy). Good luck!

**Comment by adybbroe** [comment]
Thanks, I briefly looked at both before, but seems similar to SkewT in those calculations. But I might put the same question to the MetPy team.

**Comment by tjlang** [comment]
Yes, this repository is technically a fork of https://github.com/HootWx/SkewT, made to be Python 3 compliant. So I don't have grand ambitions for it beyond that. Good luck!
